blank_issues_enabled: false
contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/REPONAME#-setup
    about: Checkout the documentation
  - name: 🚀 Feature Request
    url: https://github.com/BetaHuhn/REPONAME/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/BetaHuhn/REPONAME/discussions/new?category=q-a
    about: Ask the community for help