name: Deploy CI
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    name: Build files
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Build files
        run: npm run build
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: ":rocket: Deploy new version [skip ci]"
          commit_user_name: BetaHuhn Bot
          commit_user_email: bot@mxis.ch
          commit_author: BetaHuhn Bot <bot@mxis.ch>
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@master
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: format('dist/{0}.min.js', ${{ github.event.repository.name }})
          out_dir: format('dist/{0}', ${{ github.event.repository.name }})
          versioning: true