name: Dependabot PR CI
on:
  pull_request_target: # See related issue https://git.io/Jmcv6
  workflow_dispatch:
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' # See related GitHub article https://git.io/JmcJv
    runs-on: ubuntu-latest
    steps:
      - name: Merge minor/patch updates
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_PAT }}